Fy_p = struct('p_Cy1', 'value');

Fy_p.p_Dy1 = 'value';
Fy_p.p_Dy2 = 'value';
Fy_p.p_Dy3 = 'value';
Fy_p.p_Ey1 = 'value';
Fy_p.p_Ey2 = 'value';
Fy_p.p_Ey3 = 'value';
Fy_p.p_Ey4 = 'value';
Fy_p.p_Ky1 = 'value';
Fy_p.p_Ky2 = 'value';
Fy_p.p_Ky3 = 'value';
Fy_p.p_Hy1 = 'value';
Fy_p.p_Hy2 = 'value';
Fy_p.p_Hy3 = 'value';
Fy_p.p_Vy1 = 'value';
Fy_p.p_Vy2 = 'value';
Fy_p.p_Vy3 = 'value';
Fy_p.p_Vy4 = 'value';